<div class="row">
    <div class="col-md-12">
      <div class="panel panel-default panel-border-color panel-border-color-primary">
        <div class="panel-heading panel-heading-divider">Importação de planilhas - CVNLI
        	<span class="panel-subtitle">
        		Importar planilha para carregamento de dados de relatórios e indicadores
    		</span>
		</div>
        <div class="panel-body">
          <form action="<?php echo $this->baseUrl('/importacao-cvnli');?>" style="border-radius: 0px;" 
          	class="form-horizontal group-border-dashed" method="post" enctype="multipart/form-data">
            <div class="form-group">
              <label class="col-sm-3 control-label">Planilha CVNLI</label>
              <div class="col-sm-6">
                <input type="file" name="planilha" id="planilha" />
              </div>
            </div>
            
            <div class="form-group">
              <label class="col-sm-3 control-label">Ano de Referência:</label>
              <div class="col-sm-6">
                <?php echo $this->formSelect('ano', $this->ano, array('class'=>'form-control'), $this->arrAnos);?>
              </div>
            </div>
            
             <div class="row">
              <div class="col-xs-6">
              </div>
              <div class="col-xs-3">
                <p class="text-right">
                  <button type="submit" class="btn btn-space btn-primary">Enviar</button>
                </p>
              </div>
          	</div>
          </form>
        </div>
      </div>
    </div>
  </div>