<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Equipe</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Yata Anderson Gonzaga Masullo">
				<div class="caption">
					<h3 class="nome-equipe">Prof. Me. Yata Anderson Gonzaga Masullo</h3>
					<h4 class="cargo-equipe">Proponente</h4>
					<p>
					   
					</p>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Prof. Dr. Carlos Frederico Lago Burnett">
				<div class="caption">
					<h3>Prof. Dr. Carlos Frederico Lago Burnett</h3>
					<h4>Pesquisador</h4>
					<p>Graduado em Arquitetura pela Universidade de Buenos Aires, Argentina, 
					Mestre em Desenvolvimento Urbano pela Universidade Federal de Pernambuco, 
					Doutor em Políticas Públicas pela Universidade Federal do Maranhão.</p>
					<a href="http://lattes.cnpq.br/9094745284365149." target="_blank">Lattes: http://lattes.cnpq.br/9094745284365149.</a>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
	</div>

</div>
