<div class="be-content">
    <div class="main-content container">
    	<div class="row">
    		<div class="col-md-12 text-center">
    			<h1>Equipe</h1>
    		</div>
    	</div>
    
        <div class="gallery-container">
            <div class="item">
              <div class="photo">
                <div class="img"><img src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>" alt="Equipe">
                  <div class="over">
                    <div class="info-wrapper">
                      <div class="info">
                        <div class="title">Eliane Lima da Silva</div>
                        <div class="date">Pesquisadora</div>
                        <div class="description">Descrição do Curriculo, pesquisas, prêmios, função no projeto</div>
                        <div class="func"><a href="#"><i class="icon mdi mdi-link"></i></a><a href="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>" class="image-zoom"><i class="icon mdi mdi-search"></i></a></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="photo">
                <div class="img"><img src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>" alt="Equipe">
                  <div class="over">
                    <div class="info-wrapper">
                      <div class="info">
                        <div class="title">Eliane Lima da Silva</div>
                        <div class="date">Pesquisadora</div>
                        <div class="description">Descrição do Curriculo, pesquisas, prêmios, função no projeto</div>
                        <div class="func"><a href="#"><i class="icon mdi mdi-link"></i></a><a href="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>" class="image-zoom"><i class="icon mdi mdi-search"></i></a></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
       </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl('/assets/lib/jquery.magnific-popup/jquery.magnific-popup.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl('/assets/lib/masonry/masonry.pkgd.min.js')?>" type="text/javascript"></script>

<script type="text/javascript">
  $(window).on('load',function(){
  	App.pageGallery();
  });
</script>