<div class="main-content container">
	<div class="row">
		<div class="col-md-12 text-center">
			<h1 class="titulo-view">Equipe</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
		
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img
					src="<?php echo $this->baseUrl('/assets/img/equipe/equipe.jpg');?>"
					alt="Foto Equipe">
				<div class="caption">
					<h3>Eliane Lima da Silva</h3>
					<h4>Pesquisadora</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
						cursus tempus dolor non aliquet. Quisque blandit ipsum sit amet
						augue varius, eu vulputate erat sodales. Ut mattis diam neque,
						quis posuere sem lacinia ege</p>
				</div>
			</div>
		</div>
	</div>

</div>
