<div class="container">
	<h1 class="titulo-view">Notícias</h1>

	<div class="row">
		<div class="col-md-10">
			<table class="table table-bordered table-hover">
				<thead>
					<tr>
						<th>Titulo</th>
						<th>Texto</th>
						<th>Data de Cadastro</th>
						<th>Usuário que Cadastrou</th>
					</tr>
				</thead>
				<tbody>
          		<?php foreach($this->arrNoticias as $key => $noticia):?>
        			<tr>
        				<td><?php echo $noticia->titulo?></td>
        				<td><?php echo $noticia->texto_noticia?></td>
        				<td><?php echo $noticia->dt_cadastro?></td>
        				<td><?php echo $noticia->nome?></td>
        			</tr>
          		<?php endforeach;?>
          		</tbody>
			</table>
		</div>
  	</div>
</div>