<div class="main-content container">

	<div class="row">
        <div class="col-md-12 carrosel-bg">
            <div class="carousel slide" data-ride="carousel" id="amvm-carousel">
                <ol class="carousel-indicators">
                <li data-target="#amvm-carousel" data-slide-to="0" class="active"></li>
                <li data-target="#amvm-carousel" data-slide-to="1"></li>
                <li data-target="#amvm-carousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
        
                  <div class="item active">
                    <div class="row">
                      <div class="col-sm-9 text-center">
                        <img class="" src="assets/img/slide1.jpg">
                      </div>
                      <div class="col-sm-3">
                        <h3>Elaboração do Banco de Dados da Violência Georreferenciado</h3>
                        <p>O Banco de Dados da Violência será formatado a partir dos dados tabulados com série histórica do 
                        período de 2000 a 2012 fornecidos pelo Departamento de Informática da Sistema Único de Saúde – DATASUS de 
                        2013 e 2014 da Secretaria de Estado de Segurança Pública - SSP em nível municipal e de 2015 a outubro 
                        de 2016 do Ministério Público – MP em nível de bairro, correspondendo ao CVLI</p>
                      </div>
                    </div>
                  </div>
        
                  <div class="item">
                    <div class="row">
                      <div class="col-sm-9 text-center">
                        <img class="" src="assets/img/slide3.jpg">
                      </div>
                      <div class="col-sm-3">
                        <h3>Espacialização dos dados de CVLI</h3>
                        <p>A espacialização dos dados de CVLI foi estruturada em nível de munícipio, Conselhos Comunitário pela Paz – CCP e bairros.
                        Esta espacialização exigiu incialmente a consolidação da base cartográfica, haja vista 
                        a inexistência da Lei de Bairros que delimita seus os limites em São Luís e o não alinhamento da utilização da mesma 
                        toponímia dos bairros por parte das instituições tanto estaduais quanto municipais.</p>
                      </div>
                    </div>
                  </div>
        
                  <div class="item">
                    <div class="row">
                      <div class="col-sm-9 text-center">
                        <img class="" src="assets/img/slide2.jpg">
                      </div>
                      <div class="col-sm-3">
                      <h3>Elaboração de Mapas Temáticos e Análise situacional da violência</h3>
                        <p>A partir do processamento do Banco de Dados da Violência serão elaborados mapas temáticos com base em inferências 
                        espaciais e análises estatísticas. Infere-se ao estudo a sistematização de parâmetros de dispersão e comportamento 
                        espacial das Ocorrências Policiais e Crime Violento Letal e Intencional – CVLI, auxiliados por softwares interligados à plataforma SIG.</p>
                      </div>
                    </div>
                  </div>
                </div>
        
                <!-- Carousel Buttons Next/Prev -->
                <a data-slide="prev" href="#amvm-carousel" class="left carousel-control">
                    <i class="icon mdi mdi-chevron-left"></i>
                </a>
                <a data-slide="next" href="#amvm-carousel" class="right carousel-control">
                    <i class="icon mdi mdi-chevron-right"></i>
                </a>
              </div>                          
        </div>
    </div>

    <div class="row icones-hero icones-links">
        <div class="col-lg-12 text-center">
            <h1>
                Processo de Avaliação e Coleta dos dados
            </h1>
        </div>
        <div class="col-xs-3 col-md-3">
            <a href="<?php echo $this->baseUrl('/denuncias');?>">
                <img class="img-responsive img-link-icone" src="01.png" alt="">
                <h2>
                    Denúncias
                </h2>
            </a>
        </div>
        <div class="col-xs-3 col-md-3">
            <a href="<?php echo $this->baseUrl('/projeto');?>">
                <img class="img-responsive img-link-icone" src="02.png" alt="">
                <h2>
                    Projeto Francisca das Chagas 
                </h2>
            </a>
        </div>
        <div class="col-xs-3 col-md-3">
            <a href="<?php echo $this->baseUrl('/agrupamentos-bairros-conselhos');?>">
                <img class="img-responsive img-link-icone" src="03.png" alt="">
                <h2>
                    Agrupamento por bairros e conselhos
                </h2>
            </a>
        </div>
        <div class="col-xs-3 col-md-3">
            <a href="<?php echo $this->baseUrl('/estatisticas-resultados');?>">
                <img class="img-responsive img-link-icone" src="04.png" alt="">
                <h2>
                    Estatísticas e Resultados
                </h2>
            </a>
        </div>
    </div>
    
    <br /><br />
   
   <!--  
   <div class=row">
    	<div class="col-md-12">
    		<style>
                .embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} 
                .embed-container iframe, .embed-container object, 
                .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} 
                small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}
            </style>
            <div class="embed-container">
            <iframe width="500" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="Mapa 1 Teste"  
            		src="//franciscadaschagas.imesc.ma.gov.br/arcgis/apps/Embed/index.html?webmap=6013e06943184ad8a99432c967f27f11&amp;extent=-44.3342,-2.574,-44.166,-2.4803&amp;zoom=true&amp;scale=true&amp;disable_scroll=true&amp;theme=light"></iframe>
            </div>
    	</div>
    </div>
     -->
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
        	<div class="panel panel-default">
        		<div class="panel-body text-center painel-parceiros">
        			<h3 class="titulo-parceiro">Nossos Parceiros</h3>
        			
                    <img src="<?php echo $this->baseUrl("assets/img/parceiros/novas/fapema.jpg")?>" />
                    
                    <img src="assets/img/parceiros/mp.jpg" width="80px" />
                    
                    <img src="assets/img/parceiros/novas/lagas.jpg" />
                    
                    <img src="assets/img/parceiros/unb.png" width="80px" />
                    
                    <img src="assets/img/parceiros/novas/imesc.jpg" style="max-width: 180px" />
                    
                    <img src="assets/img/parceiros/unicef.png" width="80px" />
                    
                    <img src="assets/img/parceiros/ppgeo.png" width="80px" />
                    
                    <img src="assets/img/parceiros/novas/governo.jpg" width="300px"  style="max-width: 200px" />
                    
                    <img src="assets/img/parceiros/novas/logo-ssp-ma.png" width="180px"  style="max-width: 180px" />
                    
                    <img src="assets/img/parceiros/novas/logo-prefeitura-sao-luis.jpg" width="180px"  style="max-width: 180px" />
                    
                    <img src="assets/img/parceiros/novas/camara-sao-luis.jpg" width="120px"  style="max-width: 120px" />
                </div>
            </div>
        </div>
    </div>
</div>

<footer>
    <p>Todos os direitos reservados <?php echo date('Y')?>&copy;</p>
</footer>