<div class="main-content container">

	<div class="row">
        <div class="col-md-12 text-center">
    		<h1>Indicadores</h1>
    		
    		<div id="grafico-geral" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        </div>
    </div>

</div>

<script type="text/javascript">
Highcharts.chart('grafico-geral', {
    chart: {
        type: 'line'
    },
    title: {
        text: 'Índice de Violência'
    },
    subtitle: {
        text: 'Mensal'
    },
    xAxis: {
        categories: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
    },
    yAxis: {
        title: {
            text: 'Quantidade Crimes'
        }
    },
    plotOptions: {
        line: {
            dataLabels: {
                enabled: true
            },
            enableMouseTracking: false
        }
    },
    series: [{
        name: 'Espancamento',
        data: [7.0, 6.9, 9.5, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
    }, {
        name: 'Estrangulamento',
        data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
    }, {
        name: 'Lesão Corporal',
        data: [8.0, 3.9, 4.5, 15.5, 18.4, 20.5, 21.2, 25.5, 21.3, 15.3, 18, 30]
    } ]
});
</script>