<style>
.embed-container {
	position: relative;
	padding-bottom: 80%;
	height: 0;
	max-width: 100%;
}

.embed-container iframe, .embed-container object, .embed-container iframe
	{
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}

small {
	position: absolute;
	z-index: 40;
	bottom: 0;
	margin-bottom: -15px;
}
</style>

<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Mapas - Total de Ocorrências</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="embed-container">
				<small>
					<a href="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=5d132097818b4f5d9a89f66f2a19edd5&amp;extent=-44.5916,-2.8134,-43.7484,-2.3778&home=true&zoom=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light" style="color:#0000FF;text-align:left" target="_blank">
						Visualizar mapa grande
					</a>
				</small>
				<br />
				<iframe width="400" height="100" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="OCORRÊNCIAS DE CVNLI 2017 FEMININO" src="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=5d132097818b4f5d9a89f66f2a19edd5&amp;extent=-44.5916,-2.8134,-43.7484,-2.3778&home=true&zoom=true&previewImage=false&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
			</div>
		</div>
	</div>
</div>
