<style>
.embed-container {
	position: relative;
	padding-bottom: 80%;
	height: 0;
	max-width: 100%;
}

.embed-container iframe, .embed-container object, .embed-container iframe
	{
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}

small {
	position: absolute;
	z-index: 40;
	bottom: 0;
	margin-bottom: -15px;
}
</style>

<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Mapas - Total de Ocorrências Por Horário</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<form class="form-inline" action="<?php echo $this->url()?>" method="post">
    			<div class="form-group">
            		<label for="crimes">Selecione o dia da semana para visualizar: </label>
                    <?php echo $this->formSelect('horario', $this->horarioSelecionado, array('class'=>'form-control'), $this->horarios);?>
                    <?php echo $this->formSubmit('enviar', 'Selecionar', array('class'=>'btn btn-primary btn-lg'));?>
                </div>
            </form>
            
            <div class="embed-container">
				<small>
					<a
					href="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=cd452d94da5242f290fce3d7924010b1&amp;extent=-44.528,-2.807,-43.6848,-2.3378&home=true&zoom=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"
					style="color: #0000FF; text-align: left" target="_blank">
						Visualizar mapa grande</a></small><br>
				<iframe width="400" height="300" frameborder="0" scrolling="no"
					marginheight="0" marginwidth="0"
					title="CRIMES VIOLENTOS NÃO LETAIS FEMININO (DOMINGO) 2017"
					src="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=cd452d94da5242f290fce3d7924010b1&amp;extent=-44.528,-2.807,-43.6848,-2.3378&home=true&zoom=true&previewImage=false&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
			</div>
            
            <?php if($this->diaSemanaSelecionado === Application_Model_DadosPlanilha::HORA_0_6):?>
			<?php endif;?>
			
			<?php if($this->diaSemanaSelecionado === Application_Model_DadosPlanilha::HORA_6_12):?>
			<?php endif;?>
			
			<?php if($this->diaSemanaSelecionado === Application_Model_DadosPlanilha::HORA_12_18):?>
			<?php endif;?>
			
			<?php if($this->diaSemanaSelecionado === Application_Model_DadosPlanilha::HORA_18_24):?>
			<?php endif;?>
			
		</div>
	</div>
</div>
