<style>
.embed-container {
	position: relative;
	padding-bottom: 80%;
	height: 0;
	max-width: 100%;
}

.embed-container iframe, .embed-container object, .embed-container iframe
	{
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}

small {
	position: absolute;
	z-index: 40;
	bottom: 0;
	margin-bottom: -15px;
}
</style>

<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Mapas - Total de Ocorrências Por Horário</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<form class="form-inline" action="<?php echo $this->url()?>"
				method="post">
				<div class="form-group">
					<label for="crimes">Selecione o dia da semana para visualizar: </label>
                    <?php echo $this->formSelect('horario', $this->horarioSelecionado, array('class'=>'form-control'), $this->horarios);?>
                    <?php echo $this->formSubmit('enviar', 'Selecionar', array('class'=>'btn btn-primary btn-lg'));?>
                </div>
			</form>
            
            <?php if($this->horarioSelecionado === Application_Model_DadosPlanilha::HORA_0_6):?>
            <div class="embed-container">
				<small><a
					href="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=9022ad210cbb455f953d29714651228a&amp;extent=-44.4062,-2.6598,-43.9846,-2.4252&home=true&zoom=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"
					style="color: #0000FF; text-align: left" target="_blank">Visualizar
						mapa grande</a></small><br>
				<iframe width="400" height="300" frameborder="0" scrolling="no"
					marginheight="0" marginwidth="0"
					title="OCORRÊNCIA DE CVNLI FEMININO POR HORA (00:06 AM) 2017"
					src="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=9022ad210cbb455f953d29714651228a&amp;extent=-44.4062,-2.6598,-43.9846,-2.4252&home=true&zoom=true&previewImage=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
			</div>
			<?php endif;?>
			
			<?php if($this->horarioSelecionado === Application_Model_DadosPlanilha::HORA_6_12):?>
			<div class="embed-container">
				<small><a
					href="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=3066d427bf664a8bb50866e34cee88b2&amp;extent=-44.4025,-2.6992,-43.9809,-2.4646&home=true&zoom=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"
					style="color: #0000FF; text-align: left" target="_blank">Visualizar
						mapa grande</a></small><br>
				<iframe width="400" height="300" frameborder="0" scrolling="no"
					marginheight="0" marginwidth="0"
					title="OCORRÊNCIA DE CVNLI FEMININO POR HORA (06 - 12:00 AM) 2017"
					src="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=3066d427bf664a8bb50866e34cee88b2&amp;extent=-44.4025,-2.6992,-43.9809,-2.4646&home=true&zoom=true&previewImage=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
			</div>
			<?php endif;?>
			
			<?php if($this->horarioSelecionado === Application_Model_DadosPlanilha::HORA_12_18):?>
			<div class="embed-container">
				<small><a
					href="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=ca8374d083a2470f89cf7d95afe55833&amp;extent=-44.4624,-2.7117,-44.0408,-2.4771&home=true&zoom=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"
					style="color: #0000FF; text-align: left" target="_blank">Visualizar
						mapa grande</a></small><br>
				<iframe width="400" height="300" frameborder="0" scrolling="no"
					marginheight="0" marginwidth="0"
					title="OCORRÊNCIA DE CVNLI FEMININO POR HORA (12:00 - 18:00 PM) 2017"
					src="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=ca8374d083a2470f89cf7d95afe55833&amp;extent=-44.4624,-2.7117,-44.0408,-2.4771&home=true&zoom=true&previewImage=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
			</div>
			<?php endif;?>
			
			<?php if($this->horarioSelecionado === Application_Model_DadosPlanilha::HORA_18_24):?>
			<div class="embed-container">
				<small><a
					href="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=56e24d9939dc45e49d17576d32b91668&amp;extent=-44.4707,-2.7114,-44.0491,-2.4768&home=true&zoom=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"
					style="color: #0000FF; text-align: left" target="_blank">Visualizar
						mapa grande</a></small><br>
				<iframe width="400" height="300" frameborder="0" scrolling="no"
					marginheight="0" marginwidth="0"
					title="OCORRÊNCIA DE CVNLI FEMININO POR HORA (18:00 - 24:00 PM) 2017"
					src="//imesc.maps.arcgis.com/apps/Embed/index.html?webmap=56e24d9939dc45e49d17576d32b91668&amp;extent=-44.4707,-2.7114,-44.0491,-2.4768&home=true&zoom=true&previewImage=true&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=details&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
			</div>
			<?php endif;?>
			
		</div>
	</div>
</div>
