<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Denúncias</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body text-center">
					<h1>Para realizar uma denúncia você pode utilizar os seguintes
						meios:</h1>
					<h2>
						<a href="tel:9832235800">
							(98) 3223-5800
						</a> 
						/ 
						<a href="tel:03003135800">
							0300 3135800 
						</a>
						/ 
						<a href="tel:98992248660">
							(98) 99224-8660
						</a>
					</h2>
					
					<h1>Ou acesse o site de Denúncias:</h1>
					<h2>
						<a href="https://www.ssp.ma.gov.br/disque-denuncia/" target="_blank">
							https://www.ssp.ma.gov.br/disque-denuncia/
						</a>
					</h2>
					
					<h3>Lembrando que a denúncia é <strong>anônima.</strong></h3>
				</div>
			</div>
		</div>
	</div>
</div>