<div class="panel panel-default panel-border-color panel-border-color-primary painel-indicador">
    <div class="panel-heading panel-heading-divider">
        Bairros mais perigosos
        <span class="panel-subtitle">Total de ocorrências por bairro</span>
    </div>
    
    <div class="panel-body">
        
        <?php echo $this->partial('indicadores/filtros.phtml', array('filtros'=>$this->arrFiltros));?>        
        
        <div id="grafico-mais-ocorrencias" class="grafico-amvm shadow"></div>
    </div>
</div>
   