<div class="panel panel-default panel-border-color panel-border-color-primary painel-indicador">
    <div class="panel-heading panel-heading-divider">
        Bairros
        <span class="panel-subtitle">Total de ocorrências por bairro</span>
    </div>
    
    <div class="panel-body">
    
    	<form class="form-inline text-center form-filtros" action="<?php echo $this->url()?>" method="post">
            <div class="form-group">
        		<label for="anos"> Ano:</label> <br />
                <?php echo $this->formSelect('ano', $this->anoSelecionado, array('class'=>'form-control'), $this->filtros['anos']);?>
            </div>
            
            <div class="form-group">
        		<label for="crimes"> Tipo de Ocorrência:</label> <br />
                <?php echo $this->formSelect('crime', $this->crimeSelecionado, array('class'=>'form-control'), $this->filtros['crimes']);?>
            </div>
            
            <div class="form-group">
        		<label for="crimes">Bairro:</label> <br />
                <?php echo $this->formSelect('bairro', $this->bairrosSelecionados, array('class'=>'form-control chosen-select', 'multiple'=>'multiple'), $this->filtros['bairros']);?>
            </div>
            
            <br /><br />
            
            <p class="text-center">
                <?php echo $this->formReset('limpar', 'Limpar filtros', array('class'=>'btn btn-default btn-lg'))?>
                <?php echo $this->formSubmit('filtrar', 'Filtrar dados', array('class'=>'btn btn-primary btn-lg'));?>
            </p>
        </form>
        
<!--         <div id="grafico1linha" class="grafico-amvm shadow"></div> -->
<!--         <div id="graficoareasimples" class="grafico-amvm shadow"></div> -->
<!--         <div id="graficopizzasimples" class="grafico-amvm shadow"></div> -->
        
        
        
        <?php if (!empty($this->jsonData)):?>
        	<div id="grafico-mais-ocorrencias" class="grafico-amvm shadow"></div>
        <?php else:?>
        	<?php if($this->isPost):?>
        		<div class="text-center"><h3>Nenhum resultado encontrado para esta pesquisa.</h3></div>
        	<?php endif;?>
        <?php endif;?>
    </div>
</div>   