<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Dias da semana
        <span class="panel-subtitle">Total de ocorrências por dia da semana</span>
    </div>
    
    <div class="panel-body">
        <?php echo $this->partial('indicadores/filtros.phtml', array('filtros'=>$this->filtros));?>
    
        <div id="grafico-quantidade-dias-semana" class="grafico-amvm shadow"></div>
    </div>
</div>
   