<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Específicos por Horários do dia
        <span class="panel-subtitle">Total de ocorrências por hora do dia</span>
    </div>
    
    <div class="panel-body">
        <?php echo $this->partial('indicadores/filtros.phtml', array('filtros'=>$this->filtros));?>
        
        <div id="grafico-horarios-dia" class="grafico-amvm shadow"></div>
    </div>
</div>
   