<div class="main-content container">

  <div class="row">
    <div class="col-md-12">
      <h1 class="titulo-view">Painel de indicadores</h1>
    </div>
  </div>
    
  <div class="row">
    <div class="filtros">
      <form class="filtros-indicadores">

        <div class="col-xs-3">
          <label class="control-label">Data inicial/final </label>
          <input type="text" name="daterange" value="01/01/2015 - 01/31/2015" class="form-control indicadores-data-inicial-final daterange">
        </div>
          
          <div class="col-xs-4">
              <label class="control-label">Bairros</label>
              <select multiple="" class="select2">
                <optgroup label="Alaskan/Hawaiian Time Zone">
                  <option value="AK">Alaska</option>
                  <option value="HI">Hawaii</option>
                </optgroup>
                <optgroup label="Pacific Time Zone">
                  <option value="CA">California</option>
                  <option value="NV">Nevada</option>
                  <option value="OR">Oregon</option>
                  <option value="WA">Washington</option>
                </optgroup>
                <optgroup label="Mountain Time Zone">
                  <option value="AZ">Arizona</option>
                  <option value="CO">Colorado</option>
                  <option value="ID">Idaho</option>
                  <option value="MT">Montana</option>
                  <option value="NE">Nebraska</option>
                  <option value="NM">New Mexico</option>
                  <option value="ND">North Dakota</option>
                  <option value="UT">Utah</option>
                  <option value="WY">Wyoming</option>
                </optgroup>
                <optgroup label="Central Time Zone">
                  <option value="AL">Alabama</option>
                  <option value="AR">Arkansas</option>
                  <option value="IL">Illinois</option>
                  <option value="IA">Iowa</option>
                  <option value="KS">Kansas</option>
                  <option value="KY">Kentucky</option>
                  <option value="LA">Louisiana</option>
                  <option value="MN">Minnesota</option>
                  <option value="MS">Mississippi</option>
                  <option value="MO">Missouri</option>
                  <option value="OK">Oklahoma</option>
                  <option value="SD">South Dakota</option>
                  <option value="TX">Texas</option>
                  <option value="TN">Tennessee</option>
                  <option value="WI">Wisconsin</option>
                </optgroup>
                <optgroup label="Eastern Time Zone">
                  <option value="CT">Connecticut</option>
                  <option value="DE">Delaware</option>
                  <option value="FL">Florida</option>
                  <option value="GA">Georgia</option>
                  <option value="IN">Indiana</option>
                  <option value="ME">Maine</option>
                  <option value="MD">Maryland</option>
                  <option value="MA">Massachusetts</option>
                  <option value="MI">Michigan</option>
                  <option value="NH">New Hampshire</option>
                  <option value="NJ">New Jersey</option>
                  <option value="NY">New York</option>
                  <option value="NC">North Carolina</option>
                  <option value="OH">Ohio</option>
                  <option value="PA">Pennsylvania</option>
                  <option value="RI">Rhode Island</option>
                  <option value="SC">South Carolina</option>
                  <option value="VT">Vermont</option>
                  <option value="VA">Virginia</option>
                  <option value="WV">West Virginia</option>
                </optgroup>
              </select>
          </div>
          
          <div class="col-xs-3">
              <label class="control-label">Tipos de Crimes: </label>
              <select multiple="" class="select2">
                  <option value="cvli">CVLI</option>
                  <option value="arma-de-fogo">Arma de Fogo</option>
                  <option value="arma-branca">Arma Branca</option>
                  <option value="espancamento">Espancamento</option>
                  <option value="estrangulamento">Estrangulamento</option>
              </select>
          </div>
          
          <div class="col-xs-2 acoes-filtro">
              <button class="btn btn-space btn-default">Limpar</button>
              <button type="submit" class="btn btn-space btn-success">Filtrar</button>
          </div>
      </form>
    </div>
  </div>
    
  <div class="row">
    <div class="col-md-12">

      <div id="grafico-horario-dia" class="grafico-amvm shadow"></div>

      <div id="grafico-semana" class="grafico-amvm shadow"></div>

      <div class="botoes-controle-graficos">
       Modificar gráfico: 
       <button id="plain" class="btn btn-primary btn-lg">Padrão</button>
       <button id="inverted" class="btn btn-primary btn-lg">Invertido</button>
       <button id="polar" class="btn btn-primary btn-lg">Polar</button>
     </div>
   </div>
 </div>

</div>

<script type="text/javascript">




Highcharts.chart('grafico-horario-dia', {
    chart: {
        type: 'area'
    },
    title: {
        text: 'Indíce por Horário'
    },
    subtitle: {
        text: 'Hora'
    },
    xAxis: {
        categories: ['0h às 6h', '6h às 12h', '12h às 18h', '18h às 24h'],
        tickmarkPlacement: 'on',

    },
    yAxis: {
        title: {
            text: 'Total de Crimes'
        }
    },
    plotOptions: {
        line: {
            dataLabels: {
                enabled: true
            },
            enableMouseTracking: false
        }
    },
    series: [{
        name: 'Total de Crimes',
        data: [10, 12, 8, 25]
    }]
});


var chartSemana = Highcharts.chart('grafico-semana', {

    title: {
        text: 'Gráfico Semanal'
    },

    subtitle: {
        text: 'Padrão'
    },

    xAxis: {
        categories: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado']
    },

    series: [{
        type: 'column',
        name: 'Estrangulamento',
        colorByPoint: true,
        data: [29, 71, 106, 33, 55, 60, 120],
        showInLegend: true
    }, {
        type: 'column',
        name: 'Espancamento',
        colorByPoint: false,
        data: [29, 71, 106, 33, 55, 60, 120],
        showInLegend: true
    }]

});

$('#plain').click(function () {
	chartSemana.update({
        chart: {
            inverted: false,
            polar: false
        },
        subtitle: {
            text: 'Padrão'
        }
    });
});

$('#inverted').click(function () {
	chartSemana.update({
        chart: {
            inverted: true,
            polar: false
        },
        subtitle: {
            text: 'Invertido'
        }
    });
});

$('#polar').click(function () {
	chartSemana.update({
        chart: {
            inverted: false,
            polar: true
        },
        subtitle: {
            text: 'Polar'
        }
    });
});

</script>