<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Específicos por idade da mulher - 19 a 29 anos
        <span class="panel-subtitle">Total de ocorrências por idade</span>
    </div>
    
    <div class="panel-body">
        <div id="grafico-idade-19-29" class="grafico-amvm shadow"></div>
    </div>
</div>
   