<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Ocorrências específicas por mês
        <span class="panel-subtitle">Total de ocorrências por mês</span>
    </div>
    
    <div class="panel-body">
        <?php echo $this->partial('indicadores/filtros.phtml', array('filtros'=>$this->filtros));?>
        
        <?php if (!empty($this->jsonData)):?>
        	<div id="grafico-ocorrencia-mes" class="grafico-amvm shadow"></div>
        <?php else:?>
        	<div class="text-center"><h3>Nenhum resultado encontrado para esta pesquisa.</h3></div>
        <?php endif;?>
    </div>
    
</div>
   