<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Específicos por idade - 30 a 40 anos
        <span class="panel-subtitle">Total de ocorrências por idade</span>
    </div>
    
    <div class="panel-body">
        <?php echo $this->partial('indicadores/filtros.phtml', array('filtros'=>$this->filtros));?>
        <div id="grafico-idade-30-40" class="grafico-amvm shadow"></div>
    </div>
</div>
   