<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Específicos por idade - 41 a 50 anos
        <span class="panel-subtitle">Total de ocorrências por idade</span>
    </div>
    
    <div class="panel-body">
        <?php echo $this->partial('indicadores/filtros.phtml', array('filtros'=>$this->arrFiltros));?>
        <div id="grafico-idade-41-50" class="grafico-amvm shadow"></div>
    </div>
</div>
   