<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Ocorrências específicas por mês
        <span class="panel-subtitle">Total de ocorrências por mês</span>
    </div>
    
    <div class="panel-body">
        <div id="grafico-ocorrencia-mes-total" class="grafico-amvm shadow"></div>   
        <br /> <br />
        
        <div id="grafico-ocorrencia-mes" class="grafico-amvm shadow"></div>
    </div>
    
    
    
</div>
   