<div
	class="panel panel-default panel-border-color panel-border-color-primary painel-indicador">
	<div class="panel-heading panel-heading-divider">
		Teste <span class="panel-subtitle">Total de Ocorrência de CVLI por
			Hora ( 00: 00 as 06:00) - Feminino</span>
	</div>

	<div class="panel-body">

		<style>
        .embed-container {
        	position: relative;
        	padding-bottom: 80%;
        	height: 0;
        	max-width: 100%;
        }
        
        .embed-container iframe, .embed-container object, .embed-container iframe
        	{
        	position: absolute;
        	top: 0;
        	left: 0;
        	width: 100%;
        	height: 100%;
        }
        
        small {
        	position: absolute;
        	z-index: 40;
        	bottom: 0;
        	margin-bottom: -15px;
        }
        </style>
		<div class="embed-container">
			<small><a
				href="//www.arcgis.com/apps/Embed/index.html?webmap=3f478b2122c843879ef6e5eb3e6e2101&extent=-44.6997,-2.853,-43.8565,-2.3839&zoom=true&scale=true&details=true&legendlayers=true&active_panel=legend&basemap_gallery=true&disable_scroll=true&theme=light"
				style="color: #0000FF; text-align: left" target="_blank">Visualizar
					mapa grande</a></small><br>
			<iframe width="500" height="400" frameborder="0" scrolling="no"
				marginheight="0" marginwidth="0"
				title="Total de Ocorrência de CVLI por Hora ( 00: 00 as 06:00) - Feminino"
				src="//www.arcgis.com/apps/Embed/index.html?webmap=3f478b2122c843879ef6e5eb3e6e2101&extent=-44.6997,-2.853,-43.8565,-2.3839&zoom=true&previewImage=false&scale=true&details=true&legendlayers=true&active_panel=legend&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
		</div>
	</div>
</div>
