<div class="panel panel-default panel-border-color panel-border-color-primary">
    <div class="panel-heading panel-heading-divider">
        Tipos de Crime
        <span class="panel-subtitle">Total de ocorrências por tipo de crime</span>
    </div>
    
    <div class="panel-body">
        <?php echo $this->partial('indicadores/filtros.phtml', array('filtros'=>$this->arrFiltros));?>
    
        <div id="grafico-tipos-crime" class="grafico-amvm shadow"></div>
    </div>
</div>
   