<div class="row">
	<div class="col-md-12">
		<div class="widget widget-fullwidth be-loading">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="tools">
						<span class="icon mdi mdi-download"></span><span
							class="icon mdi mdi-more-vert"></span>
					</div>
					<div class="title">Cadastro de Usuários</div>
				</div>
				<div class="panel-body">
					<form action="<?php echo $this->url();?>" method="post">
						<?php echo $this->formHidden('id_usuario', $this->objUsuario->id_usuario)?>
    					<div class="form-group">
							<label for="email">Email</label>
							<?php echo $this->formText('email', $this->objUsuario->email, array('class' => 'form-control', 'placeholder' => 'Informe o E-mail'));?>
						</div>
						<div class="form-group">
							<label for="login">Login</label>
							<?php echo $this->formText('login', $this->objUsuario->login, array('class' => 'form-control', 'placeholder' => 'Informe o Login'));?>
						</div>
						
						<div class="form-group">
							<label for="senha">Senha</label>
							<?php echo $this->formPassword('senha', null, array('class' => 'form-control', 'placeholder' => 'Informe a Senha'));?>
						</div>
						
						<div class="form-group">
							<label for="confirmarSenha">Confirmar Senha</label> 
							<?php echo $this->formPassword('confirmarSenha', null, array('class' => 'form-control', 'placeholder' => 'Confirme a Senha'));?>
						</div>
					</form>
				</div>
			</div>

		</div>
	</div>
</div>