<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Gestor AMVM">
    <meta name="author" content="André Manoel">
    
    <title>Gestor - AMVM</title>
    
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- Le styles -->
    <?= $this->headLink()
             ->prependStylesheet($this->baseUrl('assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css'))
             ->prependStylesheet($this->baseUrl('assets/lib/material-design-icons/css/material-design-iconic-font.min.css'))
             ->prependStylesheet($this->baseUrl('assets/css/style.css'));
    ?>
  </head>
  <body>
    <div class="be-wrapper">
      <nav class="navbar navbar-default navbar-fixed-top be-top-header">
        <div class="container-fluid">
          <div class="navbar-header"><a href="index.html" class="navbar-brand"></a>
          </div>
          <div class="be-right-navbar">
            <ul class="nav navbar-nav navbar-right be-user-nav">
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                    <img src="<?php echo $this->baseUrl('assets/img/avatar.png');?>" alt="Avatar">
                    <span class="user-name"><?php echo $this->usuarioLogado->nome;?></span>
                </a>
                <ul role="menu" class="dropdown-menu">
                  <li>
                    <div class="user-info">
                      <div class="user-name"><?php echo $this->usuarioLogado->nome;?></div>
                      <div class="user-position"><?php echo $this->usuarioLogado->email;?></div>
                    </div>
                  </li>
                  <li><a href="#"><span class="icon mdi mdi-face"></span> Minha Conta</a></li>
                  <li><a href="#"><span class="icon mdi mdi-power"></span> Logout</a></li>
                </ul>
              </li>
            </ul>
            <div class="page-title"><span>Área Administrativa</span></div>
            <ul class="nav navbar-nav navbar-right be-icons-nav">
              <li class="dropdown"><a href="#" role="button" aria-expanded="false" class="be-toggle-right-sidebar"><span class="icon mdi mdi-settings"></span></a></li>
              <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><span class="icon mdi mdi-notifications"></span><span class="indicator"></span></a>
                <ul class="dropdown-menu be-notifications">
                  <li>
                    <div class="title">Notificações<span class="badge">3</span></div>
                    <div class="list">
                      <div class="be-scroller">
                        <div class="content">
                          <ul>
                            <li class="notification notification-unread"><a href="#">
                                <div class="image"><img src="assets/img/avatar2.png" alt="Avatar"></div>
                                <div class="notification-info">
                                  <div class="text"><span class="user-name">Jessica Caruso</span> accepted your invitation to join the team.</div><span class="date">2 min ago</span>
                                </div></a></li>
                            <li class="notification"><a href="#">
                                <div class="image"><img src="assets/img/avatar3.png" alt="Avatar"></div>
                                <div class="notification-info">
                                  <div class="text"><span class="user-name">Joel King</span> is now following you</div><span class="date">2 days ago</span>
                                </div></a></li>
                            <li class="notification"><a href="#">
                                <div class="image"><img src="assets/img/avatar4.png" alt="Avatar"></div>
                                <div class="notification-info">
                                  <div class="text"><span class="user-name">John Doe</span> is watching your main repository</div><span class="date">2 days ago</span>
                                </div></a></li>
                            <li class="notification"><a href="#">
                                <div class="image"><img src="assets/img/avatar5.png" alt="Avatar"></div>
                                <div class="notification-info"><span class="text"><span class="user-name">Emily Carter</span> is now following you</span><span class="date">5 days ago</span></div></a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div class="footer"> <a href="#">View all notifications</a></div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="be-left-sidebar">
        <div class="left-sidebar-wrapper"><a href="#" class="left-sidebar-toggle">Gestor AMVM</a>
          <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
              <div class="left-sidebar-content">
                <ul class="sidebar-elements">
                  <li class="divider">Menu</li>
                  <li><a href="index.html"><i class="icon mdi mdi-home"></i><span>Dashboard</span></a>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-face"></i><span>Publicações</span></a>
                    <ul class="sub-menu">
                      <li><a href="ui-alerts.html">Notícias</a>
                      </li>
                      <li><a href="ui-buttons.html">Artigos</a>
                      </li>
                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-border-all"></i><span>Planilhas</span></a>
                    <ul class="sub-menu">
                      <li class="active"><a href="tables-general.html">Importação</a>
                      </li>
                      <li><a href="tables-datatables.html">Histórico</a>
                      </li>
                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-layers"></i><span>Usuários</span></a>
                    <ul class="sub-menu">
                      <li><a href="pages-blank.html">Lista de Usuários</a>
                      </li>
                      <li><a href="pages-blank-header.html">Cadastrar</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="be-content">
        <div class="page-head">
          <h2 class="page-head-title">Tables</h2>
          <ol class="breadcrumb page-head-nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">General</li>
          </ol>
        </div>
        <div class="main-content container-fluid">
          <div class="row">
            <div class="col-sm-6">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">Basic Tables
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <thead>
                      <tr>
                        <th style="width:50%;">Name</th>
                        <th style="width:10%;">Date</th>
                        <th class="number">Rate</th>
                        <th class="number">Sales</th>
                        <th class="actions"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Penelope Thornton</td>
                        <td>23/06/2016</td>
                        <td class="number">60%</td>
                        <td class="number">639</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td>Justine Myranda</td>
                        <td>15/05/2016</td>
                        <td class="number">23%</td>
                        <td class="number">235</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td>Benji Harper</td>
                        <td>10/03/2016</td>
                        <td class="number">79%</td>
                        <td class="number">728</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td>Sherwood Clifford</td>
                        <td>18/01/2016</td>
                        <td class="number">18%</td>
                        <td class="number">135</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">Striped Tables
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <table class="table table-striped table-borderless">
                    <thead>
                      <tr>
                        <th style="width:50%;">Name</th>
                        <th style="width:10%;">Date</th>
                        <th class="number">Rate</th>
                        <th class="number">Sales</th>
                        <th class="actions"></th>
                      </tr>
                    </thead>
                    <tbody class="no-border-x">
                      <tr>
                        <td>Penelope Thornton</td>
                        <td>23/06/2016</td>
                        <td class="number">60%</td>
                        <td class="number">639</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td>Justine Myranda</td>
                        <td>15/05/2016</td>
                        <td class="number">23%</td>
                        <td class="number">235</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td>Benji Harper</td>
                        <td>10/03/2016</td>
                        <td class="number">79%</td>
                        <td class="number">728</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td>Sherwood Clifford</td>
                        <td>18/01/2016</td>
                        <td class="number">18%</td>
                        <td class="number">135</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <!--Condensed Table-->
            <div class="col-sm-6">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">Condensed Tables
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <table class="table table-condensed table-striped">
                    <thead>
                      <tr>
                        <th>Operating System</th>
                        <th class="number">Users</th>
                        <th class="number">Rebound</th>
                        <th class="actions"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Windows</td>
                        <td class="number">1.580</td>
                        <td class="number">20%</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-settings"></i></a></td>
                      </tr>
                      <tr>
                        <td>Mac OS</td>
                        <td class="number">1.322</td>
                        <td class="number">55%</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-settings"></i></a></td>
                      </tr>
                      <tr>
                        <td>Linux</td>
                        <td class="number">850</td>
                        <td class="number">45%</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-settings"></i></a></td>
                      </tr>
                      <tr>
                        <td>Android</td>
                        <td class="number">560</td>
                        <td class="number">70%</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-settings"></i></a></td>
                      </tr>
                      <tr>
                        <td>iOS</td>
                        <td class="number">450</td>
                        <td class="number">39%</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-settings"></i></a></td>
                      </tr>
                      <tr>
                        <td>Other</td>
                        <td class="number">317</td>
                        <td class="number">67%</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-settings"></i></a></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!--Hover table-->
            <div class="col-sm-6">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">Hover &amp; Image
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <table class="table table-striped table-hover">
                    <thead>
                      <tr>
                        <th style="width:37%;">User</th>
                        <th style="width:36%;">Commit</th>
                        <th>Date</th>
                        <th class="actions"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="user-avatar"> <img src="assets/img/avatar6.png" alt="Avatar">Penelope Thornton</td>
                        <td>Initial commit</td>
                        <td>Aug 6, 2015</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td class="user-avatar"> <img src="assets/img/avatar4.png" alt="Avatar">Benji Harper</td>
                        <td>Main structure markup</td>
                        <td>Jul 28, 2015</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td class="user-avatar"> <img src="assets/img/avatar5.png" alt="Avatar">Justine Myranda</td>
                        <td>Left sidebar adjusments</td>
                        <td>Jul 15, 2015</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                      <tr>
                        <td class="user-avatar"> <img src="assets/img/avatar3.png" alt="Avatar">Sherwood Clifford</td>
                        <td>Topbar dropdown style</td>
                        <td>Jun 30, 2015</td>
                        <td class="actions"><a href="#" class="icon"><i class="mdi mdi-delete"></i></a></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <!--Bordered Table-->
            <div class="col-sm-6">
              <div class="panel panel-default">
                <div class="panel-heading">Bordered Table
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <table class="table table-condensed table-hover table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Operating System</th>
                        <th class="number">Users</th>
                        <th class="number">Rebound</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Windows</td>
                        <td class="number">1.580</td>
                        <td class="number">20%</td>
                      </tr>
                      <tr>
                        <td>Mac OS</td>
                        <td class="number">1.322</td>
                        <td class="number">55%</td>
                      </tr>
                      <tr>
                        <td>Linux</td>
                        <td class="number">850</td>
                        <td class="number">45%</td>
                      </tr>
                      <tr>
                        <td>Android</td>
                        <td class="number">560</td>
                        <td class="number">70%</td>
                      </tr>
                      <tr>
                        <td>iOS</td>
                        <td class="number">450</td>
                        <td class="number">39%</td>
                      </tr>
                      <tr>
                        <td>Other</td>
                        <td class="number">317</td>
                        <td class="number">67%</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!--Hover table-->
            <div class="col-sm-6">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">Contextual Classes
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <table class="table table-striped table-borderless table-hover">
                    <thead>
                      <tr>
                        <th style="width:32%;">Class</th>
                        <th style="width:45%;">Commit</th>
                        <th>Date</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Penelope Thornton</td>
                        <td>Init	</td>
                        <td>May 6, 2016</td>
                      </tr>
                      <tr class="primary">
                        <td>Benji Harper</td>
                        <td>Main structure markup</td>
                        <td>April 22, 2016</td>
                      </tr>
                      <tr>
                        <td>Justine Myranda</td>
                        <td>Left sidebar adjusments</td>
                        <td>April 15, 2016</td>
                      </tr>
                      <tr class="success">
                        <td>Sherwood Clifford</td>
                        <td>Topbar dropdown style</td>
                        <td>April 8, 2016</td>
                      </tr>
                      <tr>
                        <td>Kristopher Donny</td>
                        <td>Left sidebar adjusments</td>
                        <td>April 15, 2016</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <!--Responsive table-->
            <div class="col-sm-12">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">Responsive Table
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <div class="table-responsive noSwipe">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th style="width:5%;">
                            <div class="be-checkbox be-checkbox-sm">
                              <input id="check1" type="checkbox">
                              <label for="check1"></label>
                            </div>
                          </th>
                          <th style="width:20%;">User</th>
                          <th style="width:17%;">Last Commit</th>
                          <th style="width:15%;">Milestone</th>
                          <th style="width:10%;">Branch</th>
                          <th style="width:10%;">Date</th>
                          <th style="width:10%;"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            <div class="be-checkbox be-checkbox-sm">
                              <input id="check2" type="checkbox">
                              <label for="check2"></label>
                            </div>
                          </td>
                          <td class="user-avatar cell-detail user-info"><img src="assets/img/avatar6.png" alt="Avatar"><span>Penelope Thornton</span><span class="cell-detail-description">Developer</span></td>
                          <td class="cell-detail"> <span>Initial commit</span><span class="cell-detail-description">Bootstrap Admin</span></td>
                          <td class="milestone"><span class="completed">8 / 15</span><span class="version">v1.2.0</span>
                            <div class="progress">
                              <div style="width: 45%" class="progress-bar progress-bar-primary"></div>
                            </div>
                          </td>
                          <td class="cell-detail"><span>master</span><span class="cell-detail-description">63e8ec3</span></td>
                          <td class="cell-detail"><span>May 6, 2016</span><span class="cell-detail-description">8:30</span></td>
                          <td class="text-right">
                            <div class="btn-group btn-hspace">
                              <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Open <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              <ul role="menu" class="dropdown-menu pull-right">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                        <tr class="online">
                          <td>
                            <div class="be-checkbox be-checkbox-sm">
                              <input id="check3" type="checkbox">
                              <label for="check3"></label>
                            </div>
                          </td>
                          <td class="user-avatar cell-detail user-info"><img src="assets/img/avatar4.png" alt="Avatar"><span>Benji Harper</span><span class="cell-detail-description">Designer</span></td>
                          <td class="cell-detail"> <span>Main structure markup</span><span class="cell-detail-description">CLI Connector</span></td>
                          <td class="milestone"><span class="completed">22 / 30</span><span class="version">v1.1.5</span>
                            <div class="progress">
                              <div style="width: 75%" class="progress-bar progress-bar-primary"></div>
                            </div>
                          </td>
                          <td class="cell-detail"><span>develop</span><span class="cell-detail-description">4cc1bc2</span></td>
                          <td class="cell-detail"><span>April 22, 2016</span><span class="cell-detail-description">14:45</span></td>
                          <td class="text-right">
                            <div class="btn-group btn-hspace">
                              <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Open <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              <ul role="menu" class="dropdown-menu pull-right">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                        <tr>
                          <td>
                            <div class="be-checkbox be-checkbox-sm">
                              <input id="check4" type="checkbox">
                              <label for="check4"></label>
                            </div>
                          </td>
                          <td class="user-avatar cell-detail user-info"><img src="assets/img/avatar5.png" alt="Avatar"><span>Justine Myranda</span><span class="cell-detail-description">Designer</span></td>
                          <td class="cell-detail"> <span>Left sidebar adjusments</span><span class="cell-detail-description">Back-end Manager</span></td>
                          <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.1.3</span>
                            <div class="progress">
                              <div style="width: 33%" class="progress-bar progress-bar-primary"></div>
                            </div>
                          </td>
                          <td class="cell-detail"><span>develop</span><span class="cell-detail-description">5477993</span></td>
                          <td class="cell-detail"><span>April 15, 2016</span><span class="cell-detail-description">10:00</span></td>
                          <td class="text-right">
                            <div class="btn-group btn-hspace">
                              <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Open <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              <ul role="menu" class="dropdown-menu pull-right">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                        <tr>
                          <td>
                            <div class="be-checkbox be-checkbox-sm">
                              <input id="check5" type="checkbox">
                              <label for="check5"></label>
                            </div>
                          </td>
                          <td class="user-avatar cell-detail user-info"><img src="assets/img/avatar3.png" alt="Avatar"><span>Sherwood Clifford</span><span class="cell-detail-description">Developer</span></td>
                          <td class="cell-detail"> <span>Topbar dropdown style</span><span class="cell-detail-description">Bootstrap Admin</span></td>
                          <td class="milestone"><span class="completed">25 / 40</span><span class="version">v1.0.4</span>
                            <div class="progress">
                              <div style="width: 55%" class="progress-bar progress-bar-primary"></div>
                            </div>
                          </td>
                          <td class="cell-detail"><span>master</span><span class="cell-detail-description">8cb98ec</span></td>
                          <td class="cell-detail"><span>April 8, 2016</span><span class="cell-detail-description">17:24</span></td>
                          <td class="text-right">
                            <div class="btn-group btn-hspace">
                              <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Open <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              <ul role="menu" class="dropdown-menu pull-right">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                        <tr class="online">
                          <td>
                            <div class="be-checkbox be-checkbox-sm">
                              <input id="check6" type="checkbox">
                              <label for="check6"></label>
                            </div>
                          </td>
                          <td class="user-avatar cell-detail user-info"><img src="assets/img/avatar.png" alt="Avatar"><span>Kristopher Donny</span><span class="cell-detail-description">Designer</span></td>
                          <td class="cell-detail"> <span>Right sidebar adjusments</span><span class="cell-detail-description">CLI Connector</span></td>
                          <td class="milestone"><span class="completed">38 / 40</span><span class="version">v1.0.1</span>
                            <div class="progress">
                              <div style="width: 98%" class="progress-bar progress-bar-primary"></div>
                            </div>
                          </td>
                          <td class="cell-detail"><span>master</span><span class="cell-detail-description">65bc2da</span></td>
                          <td class="cell-detail"><span>Mars 18, 2016</span><span class="cell-detail-description">13:02</span></td>
                          <td class="text-right">
                            <div class="btn-group btn-hspace">
                              <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Open <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                              <ul role="menu" class="dropdown-menu pull-right">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated lin</a></li>
                              </ul>
                            </div>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <nav class="be-right-sidebar">
        <div class="sb-content">
          <div class="tab-navigation">
            <ul role="tablist" class="nav nav-tabs nav-justified">
              <li role="presentation" class="active"><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">Configurações</a></li>
            </ul>
          </div>
                <div class="settings-wrapper">
                  <div class="be-scroller"><span class="category-title">Geral</span>
                    <ul class="settings-list">
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st1" id="st1"><span>
                            <label for="st1"></label></span>
                        </div><span class="name">Available</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st2" id="st2"><span>
                            <label for="st2"></label></span>
                        </div><span class="name">Enable notifications</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st3" id="st3"><span>
                            <label for="st3"></label></span>
                        </div><span class="name">Login with Facebook</span>
                      </li>
                    </ul><span class="category-title">Notifications</span>
                    <ul class="settings-list">
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" name="st4" id="st4"><span>
                            <label for="st4"></label></span>
                        </div><span class="name">Email notifications</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st5" id="st5"><span>
                            <label for="st5"></label></span>
                        </div><span class="name">Project updates</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st6" id="st6"><span>
                            <label for="st6"></label></span>
                        </div><span class="name">New comments</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" name="st7" id="st7"><span>
                            <label for="st7"></label></span>
                        </div><span class="name">Chat messages</span>
                      </li>
                    </ul><span class="category-title">Workflow</span>
                    <ul class="settings-list">
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" name="st8" id="st8"><span>
                            <label for="st8"></label></span>
                        </div><span class="name">Deploy on commit</span>
                      </li>
                    </ul>
                  </div>
                </div>
        </div>
      </nav>
    </div>
    <script src="assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
    <script src="assets/js/main.js" type="text/javascript"></script>
    <script src="assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      $(document).ready(function(){
      	//initialize the javascript
      	App.init();
      });
      
    </script>
  </body>
</html>