<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Gestor AMVM">
    <meta name="author" content="André Manoel">
    
    <title>Gestor - AMVM</title>
    
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- Le styles -->
    <?= $this->headLink()
             ->prependStylesheet($this->baseUrl('assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css'))
             ->prependStylesheet($this->baseUrl('assets/lib/material-design-icons/css/material-design-iconic-font.min.css'))
             ->prependStylesheet($this->baseUrl('assets/css/style.css'))
             ->appendStylesheet($this->baseUrl('assets/css/admin.css'))
             ->appendStylesheet($this->baseUrl('assets/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css'))
             ->appendStylesheet($this->baseUrl('assets/lib/jqvmap/jqvmap.min.css'))
             ->appendStylesheet($this->baseUrl('assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css'))
             ->appendStylesheet($this->baseUrl('assets/lib/select2/css/select2.min.css'));
    ?>
  </head>
  <body>
    <div class="be-wrapper">
      <nav class="navbar navbar-default navbar-fixed-top be-top-header">
        <div class="container-fluid">
          <div class="navbar-header">
              <a href="<?php echo $this->baseUrl('/');?>" class="logo-admin">
              	<img src="<?php echo $this->baseUrl("/assets/img/logo.png")?>" alt="Logo" style="width: 60px;">
              </a>
          </div>
          <div class="be-right-navbar">
            <ul class="nav navbar-nav navbar-right be-user-nav">
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                    <img src="<?php echo $this->baseUrl('assets/img/avatar.png');?>" alt="Avatar">
                    <span class="user-name"><?php echo $this->usuarioLogado->nome;?></span>
                </a>
                <ul role="menu" class="dropdown-menu">
                  <li>
                    <div class="user-info">
                      <div class="user-name"><?php echo $this->usuarioLogado->nome;?></div>
                      <div class="user-position"><?php echo $this->usuarioLogado->email;?></div>
                    </div>
                  </li>
                  <li><a href="#"><span class="icon mdi mdi-face"></span> Minha Conta</a></li>
                  <li><a href="<?php echo $this->baseUrl('/login/logout');?>"><span class="icon mdi mdi-power"></span> Logout</a></li>
                </ul>
              </li>
            </ul>
            <div class="page-title"><span>Área Administrativa</span></div>
          </div>
        </div>
      </nav>
      <div class="be-left-sidebar">
        <div class="left-sidebar-wrapper">
        	<a href="#" class="left-sidebar-toggle">Gestor AMVM</a>
          <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
              <div class="left-sidebar-content">
                <ul class="sidebar-elements">
                  <li class="divider">Menu</li>
                  <li>
                  	<a href="<?php echo $this->baseUrl('/gestor');?>">
                  		<i class="icon mdi mdi-home"></i>
                  		<span>Dashboard</span>
          			</a>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-face"></i><span>Publicações</span></a>
                    <ul class="sub-menu">
                      <li><a href="<?php echo $this->baseUrl('/noticias-admin');?>">Notícias</a>
                      </li>
<!--                       <li><a href="ui-buttons.html">Artigos</a> -->
<!--                       </li> -->
                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-border-all"></i><span>Planilhas</span></a>
                    <ul class="sub-menu">
                      <li><a href="<?php echo $this->baseUrl('/importacao');?>">Importação CVLI</a>
                      </li>
                      <li><a href="<?php echo $this->baseUrl('/importacao-cvnli');?>">Importação CVNLI</a>
<!--                       <li><a href="tables-datatables.html">Histórico</a> -->
<!--                       </li> -->
                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-layers"></i><span>Usuários</span></a>
                    <ul class="sub-menu">
                      <li><a href="<?php echo $this->baseUrl('/usuarios');?>">Lista de Usuários</a>
                      </li>
                      <li><a href="<?php echo $this->baseUrl('/usuarios/form');?>">Cadastrar</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="be-content">
        <div class="main-content container-fluid"> 
        	<?php
        	   if (!empty($this->messages)) {
        	       foreach($this->messages as $mensagem): 
	       ?>
	       		<div class="alert alert-<?php echo $mensagem->tipo?>" role="alert">
	       			<?php echo $mensagem->texto;?>
	       			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    	<span aria-hidden="true">&times;</span>
                    </button>
                </div>
	       <?php 
        	       endforeach;
        	       Core_Controller_Base::apagarMensagens();
        	   }
    	   ?>   
            <?php echo $this->layout()->content; ?>
        </div>
      </div>
      <nav class="be-right-sidebar">
        <div class="sb-content">
          <div class="tab-navigation">
            <ul role="tablist" class="nav nav-tabs nav-justified">
              <li role="presentation" class="active"><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">Configurações</a></li>
            </ul>
          </div>
                <div class="settings-wrapper">
                  <div class="be-scroller"><span class="category-title">Geral</span>
                    <ul class="settings-list">
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st1" id="st1"><span>
                            <label for="st1"></label></span>
                        </div><span class="name">Available</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st2" id="st2"><span>
                            <label for="st2"></label></span>
                        </div><span class="name">Enable notifications</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st3" id="st3"><span>
                            <label for="st3"></label></span>
                        </div><span class="name">Login with Facebook</span>
                      </li>
                    </ul><span class="category-title">Notifications</span>
                    <ul class="settings-list">
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" name="st4" id="st4"><span>
                            <label for="st4"></label></span>
                        </div><span class="name">Email notifications</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st5" id="st5"><span>
                            <label for="st5"></label></span>
                        </div><span class="name">Project updates</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" checked="" name="st6" id="st6"><span>
                            <label for="st6"></label></span>
                        </div><span class="name">New comments</span>
                      </li>
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" name="st7" id="st7"><span>
                            <label for="st7"></label></span>
                        </div><span class="name">Chat messages</span>
                      </li>
                    </ul><span class="category-title">Workflow</span>
                    <ul class="settings-list">
                      <li>
                        <div class="switch-button switch-button-sm">
                          <input type="checkbox" name="st8" id="st8"><span>
                            <label for="st8"></label></span>
                        </div><span class="name">Deploy on commit</span>
                      </li>
                    </ul>
                  </div>
                </div>
        </div>
      </nav>
    </div>
    
    <!-- Scripts -->
    <?= $this->headScript()
        ->appendFile($this->baseUrl('assets/lib/jquery/jquery.min.js'))
        ->appendFile($this->baseUrl('assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js'))
        ->appendFile($this->baseUrl('assets/js/main.js'))
        ->appendFile($this->baseUrl('assets/lib/bootstrap/dist/js/bootstrap.min.js'))
        ->appendFile($this->baseUrl('assets/lib/jquery-flot/jquery.flot.js'))
        ->appendFile($this->baseUrl('assets/lib/jquery-flot/jquery.flot.pie.js'))
        ->appendFile($this->baseUrl('assets/lib/jquery-flot/jquery.flot.resize.js'))
        ->appendFile($this->baseUrl('assets/lib/jquery-flot/plugins/jquery.flot.orderBars.js'))
        ->appendFile($this->baseUrl('assets/lib/jquery-flot/plugins/curvedLines.js'))
        ->appendFile($this->baseUrl('assets/lib/jquery.sparkline/jquery.sparkline.min.js'))
        ->appendFile($this->baseUrl('assets/lib/countup/countUp.min.js'))
        ->appendFile($this->baseUrl('assets/lib/jquery-ui/jquery-ui.min.js'))
        ->appendFile($this->baseUrl('assets/lib/jqvmap/jquery.vmap.min.js'))
        ->appendFile($this->baseUrl('assets/lib/jqvmap/maps/jquery.vmap.world.js'))
        ->appendFile($this->baseUrl('assets/lib/select2/js/select2.min.js'))
        ->appendFile($this->baseUrl('assets/lib/jqvmap/maps/jquery.vmap.world.js'))
    ?>
    
    <script type="text/javascript">
      $(document).ready(function(){
      	App.init();
      	App.dashboard();
      });
    </script>
  </body>
</html>