<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="">
    <?= $this->headTitle('GESTOR - Projeto Francisca das Chagas')->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css'))
        ->prependStylesheet($this->basePath('assets/lib/material-design-icons/css/material-design-iconic-font.min.css'))
        ->prependStylesheet($this->basePath('assets/css/style.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'))
        ->prependFile($this->basePath('assets/lib/jquery/jquery.min.js'))
    ?>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>


<div class="be-wrapper be-nosidebar-left">
    <!-- <img src="barra.png" alt="" style="position: absolute; top: 0px; z-index: 2000;"> -->
    <nav class="navbar navbar-default navbar-fixed-top be-top-header">
        <div class="container">
            <div class="navbar-header">
                <a href="index.html" class="navbar-brand" style="width: 100%;">
                    <p style="">
                        Avaliação e Monitoramento
                        da violência contra mulheres
                    </p>
                </a>
            </div>

        </div>
    </nav>
    <div class="be-content">
        <?= $this->content ?>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        App.init();
    });
</script>

<?= $this->inlineScript() ?>

</body>
</html>
