<div
	class="panel panel-default panel-border-color panel-border-color-primary painel-indicador">
	<div class="panel-heading panel-heading-divider">
		Ocorrências por Ano - 2017 <span class="panel-subtitle"> Densidade de
			Ocorrência de Crimes Letais no Ano de 2017 - Feminino </span>
	</div>

	<div class="panel-body">

		<style>
        .embed-container {
        	position: relative;
        	padding-bottom: 80%;
        	height: 0;
        	max-width: 100%;
        }
        
        .embed-container iframe, .embed-container object, .embed-container iframe
        	{
        	position: absolute;
        	top: 0;
        	left: 0;
        	width: 100%;
        	height: 100%;
        }
        
        small {
        	position: absolute;
        	z-index: 40;
        	bottom: 0;
        	margin-bottom: -15px;
        }
        </style>
		<div class="embed-container">
			<iframe width="500" height="400" frameborder="0" scrolling="no"
				marginheight="0" marginwidth="0"
				title="Densidade de Ocorrência de Crimes Letais no Ano de 2017 - Feminino"
				src="//www.arcgis.com/apps/Embed/index.html?webmap=2e53812c4dad4fc282237fdccc16bc91&extent=-44.6863,-2.8447,-43.8431,-2.3755&home=true&zoom=true&previewImage=false&scale=true&search=true&searchextent=true&details=true&legendlayers=true&active_panel=legend&basemap_gallery=true&disable_scroll=true&theme=light"></iframe>
		</div>
	</div>
</div>
