<div
	class="panel panel-default panel-border-color panel-border-color-primary painel-indicador">
	<div class="panel-heading panel-heading-divider">
			Ocorrências por Ano <span class="panel-subtitle"> Densidade de
			Ocorrência de Crimes Letais no Ano de <?php echo $this->selecionado?> - Feminino </span>
		
		<div class="form-filtros-mapa">
			<form action="<?php $this->url();?>" method="post">
				<label>Ano:</label>
				<?php echo $this->formSelect('ano', $this->selecionado, array(), $this->arrFiltros);?>
				<?php echo $this->formSubmit('filtrar', 'Visualizar')?>
			</form>
		</div>
	</div>

	<div class="panel-body">
		<style>
        .embed-container {
        	position: relative;
        	padding-bottom: 80%;
        	height: 0;
        	max-width: 100%;
        }
        
        .embed-container iframe, .embed-container object, .embed-container iframe
        	{
        	position: absolute;
        	top: 0;
        	left: 0;
        	width: 100%;
        	height: 100%;
        }
        
        small {
        	position: absolute;
        	z-index: 40;
        	bottom: 0;
        	margin-bottom: -15px;
        }
        </style>
		<div class="embed-container">
			<?php echo $this->mapaSelecionado;?>	
		</div>
		
		<?php echo $this->partial('indicadores-cvli/observacao.phtml');?>
	</div>
</div>
