<div
	class="panel panel-default panel-border-color panel-border-color-primary painel-indicador">
	<div class="panel-heading panel-heading-divider">
		Download do arquivo ShapeFile do Projeto
	</div>

	<div class="panel-body text-center" style="height: 300px; padding-top: 100px">
		<a class="btn-primary btn btn-lg" href="<?php echo $this->baseUrl('/download/shp_mulheres.rar')?>" target="_blank">DOWNLOAD DO ARQUIVO SHAPEFILE</a>
	</div>
</div>
