<div class="row">
	<div class="col-md-12">
		<div class="widget widget-fullwidth be-loading">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="tools">
						<a href="<?php echo $this->baseUrl('/mapas-admin/form');?>"
							class="btn btn-default">Cadastrar um mapa</a>
					</div>
					<div class="title">Mapas</div>
				</div>
				
				<div class="filtros-lista">
					<form action="<?php echo $this->url();?>" method="post">
    					<label for="ano">Ano:</label>
        				<?php echo $this->formSelect('ano', $this->anoSelecionado, array(), $this->anos);?>
        				<label>Tipo:</label>
        				<?php echo $this->formSelect('tipo', $this->tipoSelecionado, array('class'=>'mapa-tipo-select-form'), $this->tipos);?>
        				<label>Classificacao:</label>
        				
        				<span id="classificacao-tipo">
        					<?php echo $this->formSelect('classificacao', $this->classificacaoSelecionado, array(), $this->classificacao);?>
        				</span>
        				<?php echo $this->formSubmit('filtrar', 'Visualizar')?>
					</form>
				</div>
				<div class="panel-body">
					<table class="table table-bordered table-hover datatable">
						<thead>
							<tr>
								<th>Ano</th>
								<th width="20%">Titulo</th>
								<th>Visualizar Mapa</th>
								<th>Tipo</th>
								<th>Classificação</th>
								<th>Ações</th>
							</tr>
						</thead>
						<tbody>
                  		<?php foreach($this->mapas as $key => $mapa): //a($mapa);?>
        					<tr>
								<td><?php echo $mapa['ano'];?></td>
								<td><?php echo $mapa['titulo'];?></td>
								<td>Botao</td>
								<td><?php echo $mapa['tipo'];?></td>
								<td><?php echo $mapa['tipo_classificacao'];?></td>
								<td>
									<a href="<?php echo $this->baseUrl('/mapas-admin/form/id_mapa/' . $mapa['id_mapa'])?>" class="btn btn-primary">Editar</a>
									<a href="<?php echo $this->baseUrl('/mapas-admin/excluir/id_mapa/' . $mapa['id_mapa'])?>" class="btn btn-danger">Excluir</a>
								</td>
							</tr>
          				<?php endforeach;?>
                  		</tbody>
					</table>
				</div>
			</div>

		</div>
	</div>
</div>