<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Notícias</h1>
		</div>
	</div>

	<div class="row">
	<?php if(!empty($this->arrNoticias)):?>
      	<?php foreach($this->arrNoticias as $key => $noticia):?>
        	<div class="col-sm-12">
    			<div class="panel panel-default">
    				<div class="panel-heading panel-heading-divider">
    					<a href="<?php echo $this->baseUrl('/noticias/visualizar/id/' . $noticia->id_noticia);?>">
    						<?php echo $noticia->titulo?>
    					</a>
					</div>
    				<div class="panel-body">
    					<p>
                          <?php echo limitarTexto($noticia->texto_noticia, 300)?>
                        </p>
    					<a href="<?php echo $this->baseUrl('/noticias/visualizar/id/' . $noticia->id_noticia);?>">
    						Leia mais 
						</a>
    				</div>
    			</div>
    		</div>
      	<?php endforeach;?>
  	<?php else:?>
  		<div class="text-center">
  			<h3>Nenhuma notícia foi publicada até o momento.</h3>
  		</div>
  	<?php endif;?>
  </div>
</div>