<div class="main-content container">
	<div class="row">
    <div class="col-md-12">
      <h1 class="titulo-view">Notícias</h1>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-6">

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-divider">Titulo notícia</div>
        <div class="panel-body">
          <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula...
          </p>
          <a href="<?php echo $this->baseUrl('/noticias/visualizar/id/1');?>">Leia mais</a>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-divider">Titulo notícia</div>
        <div class="panel-body">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula...
          </p>
          <a href="<?php echo $this->baseUrl('/noticias/visualizar/id/1');?>">Leia mais</a>
        </div>
      </div>



    </div>
    <div class="col-sm-6">

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-divider">Titulo notícia</div>
        <div class="panel-body">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula...
          </p>
          <a href="<?php echo $this->baseUrl('/noticias/visualizar/id/1');?>">Leia mais</a>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-divider">Titulo notícia</div>
        <div class="panel-body">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula...
          </p>
          <a href="<?php echo $this->baseUrl('/noticias/visualizar/id/1');?>">Leia mais</a>
        </div>
      </div>

    </div>
  </div>


</div>