<div class="main-content container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading panel-heading-divider"><?php echo $this->noticia->titulo?></div>
              <div class="panel-body">
                <p>
                	<?php echo $this->noticia->texto_noticia?>
                </p>
                <p class="xs-mt-30 xs-mb-20">
                    <a href="<?php echo $this->baseUrl('/noticias/');?>">Voltar para notícias</a>
                </p>
              </div>
            </div>

        </div>
    </div>
</div>