<div class="main-content container">
	<div class="row">
        <div class="col-md-12 text-center">
    		<h1>Título da Notícia</h1>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="box-noticia">
                <h2>Subtitulo da Notícia</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor 
                    dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis 
                    magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula. Praesent 
                    elementum mi vel risus condimentum placerat. Nullam sem eros, scelerisque at sagittis at, 
                    venenatis id eros. Phasellus vestibulum at nisl vitae sollicitudin. Maecenas feugiat nec 
                    ante at eleifend. Vivamus pharetra massa et neque vehicula, sit amet ullamcorper nisi 
                    fringilla. Morbi sit amet velit imperdiet, sagittis tortor in, finibus magna. Quisque 
                    bibendum diam dignissim fringilla ultrices. Vivamus eget purus maximus magna egestas porttitor. 
                    Aliquam ut ante augue. Integer sit amet dui blandit, gravida ipsum eget, vehicula erat.
                </p>
                
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor 
                    dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis 
                    magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula. Praesent 
                    elementum mi vel risus condimentum placerat. Nullam sem eros, scelerisque at sagittis at, 
                    venenatis id eros. Phasellus vestibulum at nisl vitae sollicitudin. Maecenas feugiat nec 
                    ante at eleifend. Vivamus pharetra massa et neque vehicula, sit amet ullamcorper nisi 
                    fringilla. Morbi sit amet velit imperdiet, sagittis tortor in, finibus magna. Quisque 
                    bibendum diam dignissim fringilla ultrices. Vivamus eget purus maximus magna egestas porttitor. 
                    Aliquam ut ante augue. Integer sit amet dui blandit, gravida ipsum eget, vehicula erat.
                </p>
                
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor 
                    dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis 
                    magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula. Praesent 
                    elementum mi vel risus condimentum placerat. Nullam sem eros, scelerisque at sagittis at, 
                    venenatis id eros. Phasellus vestibulum at nisl vitae sollicitudin. Maecenas feugiat nec 
                    ante at eleifend. Vivamus pharetra massa et neque vehicula, sit amet ullamcorper nisi 
                    fringilla. Morbi sit amet velit imperdiet, sagittis tortor in, finibus magna. Quisque 
                    bibendum diam dignissim fringilla ultrices. Vivamus eget purus maximus magna egestas porttitor. 
                    Aliquam ut ante augue. Integer sit amet dui blandit, gravida ipsum eget, vehicula erat.
                </p>
                
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at risus porttitor dolor 
                    dignissim finibus luctus vitae diam. Cras condimentum urna a pretium commodo. Etiam quis 
                    magna ac orci laoreet semper a nec urna. Ut suscipit ligula in tempor vehicula. Praesent 
                    elementum mi vel risus condimentum placerat. Nullam sem eros, scelerisque at sagittis at, 
                    venenatis id eros. Phasellus vestibulum at nisl vitae sollicitudin. Maecenas feugiat nec 
                    ante at eleifend. Vivamus pharetra massa et neque vehicula, sit amet ullamcorper nisi 
                    fringilla. Morbi sit amet velit imperdiet, sagittis tortor in, finibus magna. Quisque 
                    bibendum diam dignissim fringilla ultrices. Vivamus eget purus maximus magna egestas porttitor. 
                    Aliquam ut ante augue. Integer sit amet dui blandit, gravida ipsum eget, vehicula erat.
                </p>
            </div>
        </div>
    </div>
</div>