<div class="main-content container">
	<div class="row">
		<div class="col-md-12 text-center">
			<h1>Contato</h1>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6 text-center">
        	<h3>Para sugestões, dúvidas ou outros assuntos nos envie uma mensagem preenchendo o formulário abaixo.</h3>
        
			<form action="/contato" method="post">
				<div class="form-group">
					<input type="text" class="form-control" id="nome" placeholder="Seu nome" name="nome" />
				</div>
				
				<div class="form-group">
					<input type="text" class="form-control" id="email" placeholder="Seu Email" name="email" />
				</div>
				
				<div class="form-group">
					<input type="text" class="form-control" id="assunto" placeholder="Digite o Assunto" name="assunto" />
				</div>
				
				<div class="form-group">
					<textarea class="form-control" id="mensagem" placeholder="Digite a mensagem" name="mensagem" ></textarea>
				</div>
				
				<button type="submit" class="btn btn-primary btn-lg btn-block">ENVIAR</button>
			</form>
		</div>
		<div class="col-md-3"></div>
	</div>
	

</div>