<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Sobre o Projeto</h1>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">
					<h2>Conheça o projeto Francisca das Chagas</h2>
					<p>
						Avaliar a violência contra a mulher na Região Metropolitana de São Luís (MA) 
						é o principal objetivo do projeto Francisca das Chagas, criado pelo Governo 
						do Estado do Maranhão, em uma parceria do Instituto Maranhense de Estudos 
						Socioeconômicos e Cartográficos (IMESC) com a Secretaria de Segurança Pública do 
						Estado do Maranhão (SSP-MA), Secretaria de Estado de Direitos Humanos e 
						Participação Popular (SEDIHPOP), Prefeitura e Câmara Municipais de São Luís, 
						além do Ministério Público do Maranhão (MPMA).
					</p>
					
					<p>
						O nome do projeto homenageia a sindicalista rural Francisca das Chagas Silva, 
						vítima de feminicídio aos 34 anos. Ela foi encontrada morta no município de 
						Miranda do Norte, em fevereiro de 2016.
					</p>
					
					<p>
						Negra, mulher e militante das causas feministas, Francisca das Chagas Silva inspira 
						o debate por democracia, justiça, autonomia, igualdade e liberdade aos direitos das mulheres.
						O projeto apresenta um Painel de Monitoramento de Dados da Violência contra Mulher para 
						integração de ações entre o Sistema Único de Saúde (SUS) e a SSP-MA.
					</p>
					
					<p>
						O painel, além de analisar os dados de violência dos municípios de São Luís e elaborar 
						o Banco de Dados Geoespacial da Violência, irá, também, mapear a dinâmica espaço-temporal 
						das ocorrências policiais (crime violento contra a mulher), além do desenvolvimento 
						de metodologias direcionadas a otimização do planejamento e a tomada de decisão 
						interligada ao SUS, visando à proteção dos direitos e liberdades individuais, 
						bem como a proteção da vida e da propriedade dos cidadãos.
					</p>
				</div>
			</div>
		</div>
	</div>
</div>