<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Sobre o Projeto</h1>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">
					<h2>Objetivo Geral</h2>
					<p>
						Avaliar a violência contra mulher no município de São Luís - MA 
						entre os anos de 2000 a 2015, construindo o Painel de Monitoramento de Dados 
						da Violência contra Mulher para integração de ações entre o Sistema Único de 
						Saúde – SUS e a Secretaria Estadual de Segurança Pública - SSP.
					</p>
					
					<h2>Objetivos Específicos</h2>
					<ul>
						<li>Analisar os dados de violência dos municípios de São Luís - MA;</li>
						<li>Elaborar o Banco de Dados Geoespacial da Violência;</li>
						<li>Mapear a dinâmica espaço-temporal das ocorrências policiais, crime violento contra a mulher;</li>
						<li>Desenvolver metodologias direcionadas a otimização do planejamento e a tomada de decisão interligado 
						ao SUS, visando à proteção dos direitos e liberdades individuais bem como a proteção da vida e 
						da propriedade dos cidadãos.</li>
					</ul>
					
					<h2>Metodologia</h2>
					<p>
    					O Banco de Dados da Violência será formatado a partir dos dados tabulados fornecidos pela Secretaria de 
    					Estado de Segurança Pública - SSP e Ministério Público - MP, relativos às Ocorrências Policiais e 
    					Mortes Violentas Intencionais – MVI como:
    					<ul>
    						<li>Quantitativo de Ocorrências por Município;</li>
    						<li>Endereço (Bairro, Rua, Número e Ponto de Referências); Gênero;</li>
    						<li>Cor;</li>
    						<li>Faixa Etária;</li>
    						<li>Data e Horário.</li>
    					</ul>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>