<div class="row">
    <div class="col-md-12">
      <div class="panel panel-default panel-border-color panel-border-color-primary">
        <div class="panel-heading panel-heading-divider">Área Administrativa - Acesso Rápido</div>
        <div class="panel-body" style="height: 200px; padding-top: 50px;">
          
          <div class="row">
          	<div class="col-md-6 text-center">
          		<a href="<?php echo $this->baseUrl('/importacao');?>" class="btn btn-lg btn-default">
          			Importação de Planilhas CVLI
      			</a>
          	</div>
          	
          	<div class="col-md-6 text-center">
          		<a href="<?php echo $this->baseUrl('/importacao-cvnli');?>" class="btn btn-lg btn-default">
          			Importação de Planilhas CVNLI
      			</a>
          	</div>
          	
          </div>
          <br />
          <div class="row">
          	<div class="col-md-4 text-center">
          		<a href="<?php echo $this->baseUrl('/noticias-admin');?>" class="btn btn-lg btn-default">
          			Publicações
      			</a>
          	</div>
          	
          	<div class="col-md-4 text-center">
          		<a href="<?php echo $this->baseUrl('/usuarios');?>" class="btn btn-lg btn-default">
          			Controle de Usuários
      			</a>
          	</div>
          	
          	<div class="col-md-4 text-center">
          		<a href="<?php echo $this->baseUrl('/mensagens');?>" class="btn btn-lg btn-default">
          			Mensagens Enviadas
      			</a>
          	</div>
          </div>
        </div>
      </div>
    </div>
  </div>