<div class="main-content container">

	<div class="row">
        <div class="col-md-12">
            <div class="carousel slide" data-ride="carousel" id="amvm-carousel">
                <ol class="carousel-indicators">
                <li data-target="#amvm-carousel" data-slide-to="0" class="active"></li>
                <li data-target="#amvm-carousel" data-slide-to="1"></li>
                <li data-target="#amvm-carousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
        
                  <div class="item active">
                    <div class="row">
                      <div class="col-sm-9 text-center">
                        <img class="" src="assets/img/slide1.jpg">
                      </div>
                      <div class="col-sm-3">
                        <h3>Elaboração do Banco de Dados da Violência Georreferenciado</h3>
                        <p>O Banco de Dados da Violência será formatado a partir dos dados tabulados com série histórica do 
                        período de 2000 a 2012 fornecidos pelo Departamento de Informática da Sistema Único de Saúde – DATASUS de 
                        2013 e 2014 da Secretaria de Estado de Segurança Pública - SSP em nível municipal e de 2015 a outubro 
                        de 2016 do Ministério Público – MP em nível de bairro, correspondendo ao CVLI</p>
                      </div>
                    </div>
                  </div>
        
                  <div class="item">
                    <div class="row">
                      <div class="col-sm-9 text-center">
                        <img class="" src="assets/img/slide3.jpg">
                      </div>
                      <div class="col-sm-3">
                        <h3>Espacialização dos dados de CVLI</h3>
                        <p>A espacialização dos dados de CVLI foi estruturada em nível de munícipio, Conselhos Comunitário pela Paz – CCP e bairros.
                        Esta espacialização exigiu incialmente a consolidação da base cartográfica, haja vista 
                        a inexistência da Lei de Bairros que delimita seus os limites em São Luís e o não alinhamento da utilização da mesma 
                        toponímia dos bairros por parte das instituições tanto estaduais quanto municipais.</p>
                      </div>
                    </div>
                  </div>
        
                  <div class="item">
                    <div class="row">
                      <div class="col-sm-9 text-center">
                        <img class="" src="assets/img/slide2.jpg">
                      </div>
                      <div class="col-sm-3">
                      <h3>Elaboração de Mapas Temáticos e Análise situacional da violência</h3>
                        <p>A partir do processamento do Banco de Dados da Violência serão elaborados mapas temáticos com base em inferências 
                        espaciais e análises estatísticas. Infere-se ao estudo a sistematização de parâmetros de dispersão e comportamento 
                        espacial das Ocorrências Policiais e Crime Violento Letal e Intencional – CVLI, auxiliados por softwares interligados à plataforma SIG.</p>
                      </div>
                    </div>
                  </div>
                </div>
        
                <!-- Carousel Buttons Next/Prev -->
                <a data-slide="prev" href="#amvm-carousel" class="left carousel-control"><i class="fa fa-chevron-left"></i></a>
                <a data-slide="next" href="#amvm-carousel" class="right carousel-control"><i class="fa fa-chevron-right"></i></a>
              </div>                          
        </div>
    </div>

    <div class="row icones-hero">
        <div class="col-lg-12 text-center">
            <h1>
                Processo de Avaliação e Coleta dos dados
            </h1>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="01.png" alt="">
            <h2>
                Denúncias
            </h2>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="02.png" alt="">
            <h2>
                Coleta de dados
            </h2>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="03.png" alt="">
            <h2>
                Agrupamento por bairros e conselhos
            </h2>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="04.png" alt="">
            <h2>
                Estatísticas e Resultados
            </h2>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
        	<div class="panel panel-default">
        		<div class="panel-body text-center painel-parceiros">
        			<h2 class="titulo-parceiro">Nossos Parceiros</h2>
                    <img src="assets/img/parceiros/imesc.jpg" width="250px" />
                    
                    <img src="assets/img/parceiros/governo.jpg" width="430px" />
                    
                    <img src="assets/img/parceiros/fapema.png" width="200px" />
                    
                    <img src="assets/img/parceiros/lagas.jpg" width="250px" />
                    
                    <img src="assets/img/parceiros/mp.jpg" width="100px" />
                    
                    <img src="assets/img/parceiros/unb.png" width="100px" />
                    
                    <img src="assets/img/parceiros/unicef.png" width="100px" />
                    
                    <img src="assets/img/parceiros/ppgeo.png" width="150px" />
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-6">
            <div class="panel panel-default">
                <div class="panel-heading hero-title"><span class="title">Links úteis</span></div>
                <div class="panel-body ">
                    <ul class="list-unstyled">
                        <li>
                            <a href="http://imesc.ma.gov.br/portal/Home" target="_blank">IMESC</a>
                        </li>
                        <li>
                            <a href="http://portalsaude.saude.gov.br/" target="_blank">Ministério da Saúde</a>
                        </li>
                        <li>
                            <a href="http://www.fapema.br/" target="_blank">FAPEMA</a>
                        </li>
                        <li>
                            <a href="http://www.mpma.mp.br/" target="_blank">Ministério Público do Maranhão</a>
                        </li>
                        <li>
                            <a href="http://www.unb.br/" target="_blank">UNB - Universidade de Brasília</a>
                        </li>
                        <li>
                            <a href="https://www.unicef.org/brazil/pt/" target="_blank">UNICEF - Brasil</a>
                        </li>
                        <li>
                            <a href="http://www.ppgeo.uema.br/" target="_blank">PPGEO MA - Pós-graduação</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="panel panel-default">
                <div class="panel-heading hero-title"><span class="title">Publicações</span></div>
                <div class="panel-body hero-text">
                    <ul class="list-unstyled">
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsum dolor sit amet</p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsum</p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit </p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsumamet ipsum dolor sit amet</p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsum dolor amet</p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsum dolor amet</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>