<div class="main-content container">
    <div class="row icones-hero">
        <div class="col-lg-12">
            <h1>
                Processo de Avaliação (infográfico)
            </h1>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="01.png" alt="">
            <h2>
                Denúncias
            </h2>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="02.png" alt="">
            <h2>
                Coleta de dados
            </h2>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="03.png" alt="">
            <h2>
                Agrupamento por bairros e conselhos
            </h2>
        </div>
        <div class="col-xs-3 col-md-3">
            <img class="img-responsive" src="04.png" alt="">
            <h2>
                Estatísticas & Resultados
            </h2>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-4">
            <div class="panel panel-default">
                <div class="panel-heading hero-title"><span class="title">Parceiros</span></div>
                <div class="panel-body hero-text">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam voluptatem excepturi, nobis sequi tempora in officia aperiam maiores odit repudiandae sit totam doloremque officiis explicabo, ipsam mollitia. Recusandae suscipit, facilis.

                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae dolor perferendis impedit, doloremque debitis. Dolores animi illo minima doloremque, cum aliquam reiciendis, deserunt saepe culpa quam repellat recusandae? Odio, sequi.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-xs-8">
            <img src="slide01.jpg" class="img-responsive" alt="">
        </div>
    </div>

    <div class="row">
        <div class="col-xs-6">
            <div class="panel panel-default">
                <div class="panel-heading hero-title"><span class="title">Links úteis</span></div>
                <div class="panel-body ">
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                        <li>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                        <li>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                        <li>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                        <li>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="panel panel-default">
                <div class="panel-heading hero-title"><span class="title">Publicações</span></div>
                <div class="panel-body hero-text">
                    <ul class="list-unstyled">
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsum dolor sit amet</p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsum</p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit </p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsumamet ipsum dolor sit amet</p>
                        </li>
                        <li>
                            <p>Lorem ipsum dolor sit amet ipsum dolor amet</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>