<div class="main-content container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="titulo-view">Estatísticas e Resultados</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="main-content container">
				<div class="row">
					<div class="panel panel-default">
						<div class="panel-body">
							<br />
							<div class="row">
								<div class="col-md-4">
									<div class="thumbnail text-center">
										<img src="<?php echo $this->baseUrl('/assets/img/img-indicadores.jpg')?>" alt="Indicadores">
										<div class="caption">
											<h3>Indicadores</h3>
											<p>
												Trata‐se  de  um  referencial  metodológico  que  permitirá  a governos  (Federal,  estaduais  e  municipais),  
												áreas  ou  domínios  de políticas públicas, conjuntos de organizações, organizações públicas e suas  unidades  
												definirem  e  mensurarem  o índice de violência em São Luís - Maranhão.
											</p>
											<p>
												<a href="#" class="btn btn-primary" role="button">Acessar</a>
											</p>
										</div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="thumbnail text-center">
										<img src="<?php echo $this->baseUrl('/assets/img/img-mapas.jpg')?>" alt="Mapas">
										<div class="caption">
											<h3>Mapas</h3>
											<p>
												Mapas interativos para acompanhamentos dos indicadores, e principais características 
												da pesquisa sobre violência contra a mulher em São Luís.
											</p>
											<p>
												<a href="#" class="btn btn-primary" role="button">Acessar</a>
											</p>
										</div>
									</div>
								</div>
								
								<div class="col-md-4">
									<div class="thumbnail text-center">
										<img src="<?php echo $this->baseUrl('/assets/img/img-pesquisa.jpg')?>" alt="Pesquisa">
										<div class="caption">
											<h3>Projeto de Pesquisa</h3>
											<p>
												O estudo pretende sobrepor indicadores espaciais em nível de Município, Conselhos, Bairro e 
												Setor Censitário, com a finalidade de correlacionar as ocorrências dos Crimes Violentos Letais 
												Intencionais – CVLI e os indicadores sociais, econômicos do municípios de São Luís
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>